Algoritmo "teste_enquanto"
// Curso       : [Algoritmos e Lógica de Programação 2022]
// Professor   : Nelio Alves
// Descrição   :
// Autor(a)    : William Felix de Souza
// Data atual  : 07/06/2022
Var

   x, soma : inteiro

Inicio

   escreva ("Digite o promeiro numero: ")
   leia(x)

   soma <- 0

   enquanto x <> 0 faca
      soma <- soma + x
      escreva ("Digite outro numero: ")
      leia(x)
   fimenquanto

   escreval ("SOMA = ", soma)


Fimalgoritmo